import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { Toaster } from 'react-hot-toast';
import AddTodoField from '@components/AddTodoField';
import { AuthBase } from '@components/auth/AuthBase';
import Todo from '@components/Todo';
import DraggableContainer from '@components/draggable/DraggableContainer';
import { useFetchMeQuery, useFetchTodosQuery } from '../generated/graphql';
import Column from '@components/draggable/Column';
import Header from '@components/Header';

const columns = [
  {
    id: 'column-1',
    title: 'To do',
    status: false,
  },
  {
    id: 'column-2',
    title: 'Completed',
    status: true,
  },
];

const Home: NextPage = () => {
  const [authModal, setAuthModal] = useState(false);
  const [{ data, fetching }] = useFetchMeQuery();
  const [{ data: todoData, fetching: todoFetching }] = useFetchTodosQuery();

  return (
    <div className='container mx-auto'>
      <Head>
        <title>TodoNG</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header fetching={fetching} userData={data} setAuthModal={setAuthModal} />
      <main className='max-w-[640px] mx-auto'>
        <AddTodoField />
        {todoFetching ? (
          [1, 2, 3].map((i) => (
            <div role='status' className='animate-pulse' key={i}>
              <div className='h-12 bg-gray-200 rounded-lg mb-4' />
              <span className='sr-only'>Loading...</span>
            </div>
          ))
        ) : todoData?.returnAllTodo.length ? (
          <DraggableContainer allTodo={todoData?.returnAllTodo}>
            {columns.map((col) => (
              <Column title={col.title} key={col.id} id={col.id}>
                {todoData?.returnAllTodo.map(
                  (todo, idx) =>
                    todo.completed === col.status && (
                      <Todo
                        item={todo}
                        key={todo.id}
                        isMe={data?.me}
                        idx={idx}
                      />
                    )
                )}
              </Column>
            ))}
          </DraggableContainer>
        ) : (
          <p className='text-sm p-2 bg-gray-200 rounded'>
            Hai....the todo list is empty😬. Please, start by adding a todo🤗
          </p>
        )}
      </main>
      <AuthBase open={authModal} setOpen={setAuthModal} />
      <Toaster />
    </div>
  );
};

export default Home;
