import type { NextPage } from 'next';
import Head from 'next/head';
import { AuthBase } from '../components/auth/AuthBase';

const Home: NextPage = () => {
  return (
    <div className='container mx-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='text-3xl font-bold underline'>Hello world!</h1>
      <AuthBase />
    </div>
  );
};

export default Home;
